import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
const { chromium } = createRequire(import.meta.url)('playwright')
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const context = await browser.newContext({ viewport: { width: 1280, height: 800 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const gateway = `127.0.0.1:${process.env.BENGLE_FIXTURE_PORT ?? 5396}`
const homeUrl = `http://127.0.0.1:5173/?gateway=${gateway}`
const control = body => fetch(`http://${gateway}/test-control`, { method: 'POST', body: JSON.stringify(body) })
const state = async () => (await fetch(`http://${gateway}/test-state`)).json()
const panel = name => page.locator('.hardware-panel').filter({ has: page.getByRole('heading', { name, exact: true }) })
await context.addInitScript(() => {
  sessionStorage.setItem('bestpresso.fullscreen-prompt-dismissed.v1', 'true')
  localStorage.setItem('bestpresso.preferences.v1', JSON.stringify({ language: 'en', waterCriticalLevelMl: 1999, waterWarningLevelMl: 100 }))
})
try {
  await control({ reset: true, model: 'Bengle', connected: true, sensor: true, currentLevel: 50, state: 'idle', failPath: '', powerCycle: true })
  await page.goto(homeUrl)
  await page.waitForFunction(() => document.querySelector('.reservoir-reading')?.textContent.includes('50 mm'))
  assert.match(await page.locator('.reservoir-reading').innerText(), /1,453/)
  assert.equal(await page.locator('.reservoir-reading[role=meter]').count(), 0)
  await page.waitForFunction(() => document.querySelector('.utility-card--scale')?.textContent.includes('10.0'))
  for (const viewport of [{ width: 1280, height: 800 }, { width: 1024, height: 768 }, { width: 390, height: 844 }]) {
    await page.setViewportSize(viewport)
    const steamCard = page.locator('.drink-card.utility-card--steam')
    if (await steamCard.evaluate(element => element.classList.contains('is-compact'))) await steamCard.locator('.drink-card__expand').click()
    await steamCard.locator('.probe-reading').waitFor()
    assert.match(await steamCard.locator('.probe-reading').innerText(), /42/)
    await page.evaluate(() => document.fonts.ready)
    await steamCard.scrollIntoViewIfNeeded()
    await page.waitForFunction(() => {
      const card = document.querySelector('.drink-card.utility-card--steam')
      const probe = card?.querySelector('.probe-reading')?.getBoundingClientRect()
      const metrics = card?.querySelector('.drink-card__steam-secondary')?.getBoundingClientRect()
      const bounds = card?.getBoundingClientRect()
      return probe && metrics && bounds && probe.bottom <= metrics.top && metrics.bottom <= bounds.bottom + 1
    })
    await page.waitForFunction(() => {
      const bounds = document.querySelector('.drink-card.utility-card--steam').getBoundingClientRect()
      return bounds.width >= 200 && bounds.right <= innerWidth
    })
    await page.screenshot({ path: `artifacts/bengle-probe-${viewport.width}.png`, fullPage: true })
  }
  await page.setViewportSize({ width: 1280, height: 800 })
  assert.equal((await state()).sockets.filter(path => path.startsWith('/ws/v1/sensors/')).join(), '/ws/v1/sensors/bengle-milkprobe/snapshot')
  await page.screenshot({ path: 'artifacts/bengle-home-desktop.png', fullPage: true })
  await page.goto(`${homeUrl}&page=settings`)
  await page.getByRole('button', { name: 'Alerts & water', exact: true }).click()
  await page.getByRole('button', { name: 'Decrease Warn me', exact: true }).click()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  assert.deepEqual(await page.evaluate(() => {
    const preferences = JSON.parse(localStorage.getItem('bestpresso.preferences.v1'))
    return [preferences.waterWarningLevelMl, preferences.waterCriticalLevelMl]
  }), [90, 1999])
  await page.getByRole('button', { name: 'Machine hardware', exact: true }).click()
  const cup = panel('Cup warmer')
  await cup.getByRole('checkbox').waitFor()
  await page.waitForFunction(() => !document.querySelector('.hardware-panel fieldset')?.disabled)
  assert.equal(await cup.getByRole('checkbox').isChecked(), false)
  await cup.getByRole('button', { name: 'Increase Target temperature (°C)', exact: true }).click()
  await cup.getByRole('button', { name: 'Apply', exact: true }).click()
  await cup.getByText('Confirmed by machine').waitFor()
  assert.equal((await state()).warmer.enabled, false)
  const warmerUrl = '**/api/v1/machine/cupWarmer'
  await page.route(warmerUrl, route => route.request().method() === 'PUT'
    ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ reason: 'simulated heater rejection' }) })
    : route.continue())
  await cup.getByRole('button', { name: 'Increase Target temperature (°C)', exact: true }).click()
  await cup.getByRole('button', { name: 'Apply', exact: true }).click()
  await cup.getByRole('alert').waitFor()
  const rejection = cup.getByText('/machine/cupWarmer: 503 - simulated heater rejection', { exact: true })
  await rejection.waitFor()
  await page.waitForResponse(response => response.url().endsWith('/machine/cupWarmer') && response.request().method() === 'GET' && response.status() === 200)
  assert.equal(await cup.getByRole('alert').count(), 1)
  await cup.getByRole('button', { name: 'Reload', exact: true }).click()
  await cup.getByRole('alert').waitFor({ state: 'detached', timeout: 3000 })
  assert.equal(await rejection.count(), 0)
  await page.unroute(warmerUrl)
  await cup.getByRole('checkbox').check()
  await cup.getByRole('button', { name: 'Apply', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.hardware-panel output').length >= 3)
  assert.equal((await state()).warmer.enabled, true)
  const preheat = panel('Scheduled preheat')
  await preheat.getByRole('checkbox').check()
  await preheat.getByRole('button', { name: 'Apply', exact: true }).click()
  await preheat.getByText('Confirmed by machine').waitFor()
  assert.equal((await state()).preheat.enabled, true)
  const lighting = panel('Lighting')
  await lighting.locator('input[type=color]').first().fill('#112233')
  await lighting.getByRole('button', { name: 'Apply', exact: true }).click()
  await lighting.getByText('Confirmed by machine').waitFor()
  assert.equal((await state()).palette.frontStrip.awake, '111122223333')
  const calibration = panel('Load cells')
  page.on('dialog', dialog => dialog.accept())
  await calibration.getByRole('button', { name: 'Zero', exact: true }).click()
  await calibration.getByText(/zeroing/).waitFor()
  await calibration.getByText(/complete/).waitFor()
  await calibration.getByRole('button', { name: 'Latch mass', exact: true }).click()
  await calibration.getByText(/calLatch/).waitFor()
  await calibration.getByRole('button', { name: 'Abort', exact: true }).click()
  await calibration.getByText(/idle/).waitFor()
  await page.screenshot({ path: 'artifacts/bengle-settings-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('.settings-content__body').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: 'artifacts/bengle-settings-mobile.png', fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await cup.getByRole('heading').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'artifacts/bengle-cup-warmer-mobile.png', fullPage: true })
  await lighting.getByRole('heading', { level: 2 }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'artifacts/bengle-lighting-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1024, height: 768 })
  await page.screenshot({ path: 'artifacts/bengle-settings-tablet.png', fullPage: true })
  await control({ connected: false, powerCycle: true })
  await cup.waitFor({ state: 'detached', timeout: 15000 })
  await control({ connected: true })
  await cup.getByRole('checkbox').waitFor({ timeout: 15000 })
  assert.equal(await cup.getByRole('checkbox').isChecked(), false)
  const connections = (await state()).sockets
  assert.equal(connections.filter(path => path === '/ws/v1/machine/waterLevels').length, 1)
  await control({ model: 'DE1' })
  await cup.waitFor({ state: 'detached', timeout: 15000 })
  assert.equal(await page.locator('.hardware-panel').count(), 0)
  await control({ model: 'Bengle' })
  await cup.getByRole('checkbox').waitFor({ timeout: 15000 })
  await control({ failPath: '/api/v1/machine/cupWarmer/preheat' })
  await preheat.getByRole('button', { name: 'Reload', exact: true }).click()
  await preheat.getByText('Unavailable', { exact: true }).waitFor()
  assert.equal(await preheat.getByRole('checkbox').count(), 0)
  await control({ failPath: '', state: 'steam' })
  await page.locator('.live-utility-overlay').waitFor({ timeout: 15000 })
  await page.locator('.live-utility-overlay .probe-reading').waitFor()
  await control({ sensor: false })
  await page.locator('.live-utility-overlay .probe-reading').waitFor({ state: 'detached', timeout: 15000 })
  await control({ state: 'idle', sensor: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(homeUrl)
  await page.waitForFunction(() => document.querySelector('.reservoir-reading')?.textContent.includes('50 mm'))
  await page.screenshot({ path: 'artifacts/bengle-home-mobile.png', fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  assert.deepEqual(errors, [])
  console.log('Bengle browser checks passed: independent water warning, Decaid sensor discovery and selection, manual reload recovery, writes, calibration, reconnect, swap, preheat failure, sensor detachment, desktop/tablet/mobile.')
} finally { await browser.close() }
