import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { en } from '../src/i18n/en/index.ts'
import { LANGUAGES, languageRegistry, isLanguage } from '../src/i18n/registry.ts'
import { translationStatus, validateCatalog, type ReviewedSources } from '../src/i18n/validation.ts'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const command = process.argv[2] ?? 'check'
const readReviewed = (language: string): ReviewedSources => {
  const file = path.join(root, 'src/i18n/reviewed', `${language}.json`)
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {}
}

if (command === 'review') {
  const language = process.argv[3]
  const keys = process.argv.slice(4)
  if (!isLanguage(language) || language === 'en' || !keys.length) throw new Error('Usage: npm run i18n:review -- de token.name [token.name ... | --all]')
  const catalog = await languageRegistry[language].load()
  const errors = validateCatalog(en, catalog, languageRegistry[language].locale)
  if (errors.length) throw new Error(errors.join('\n'))
  const reviewed = readReviewed(language)
  for (const key of keys.includes('--all') ? Object.keys(catalog) : keys) {
    if (!(key in en) || !catalog[key as keyof typeof en]) throw new Error(`Cannot acknowledge missing/unknown token: ${key}`)
    reviewed[key] = { source: en[key as keyof typeof en], translation: catalog[key as keyof typeof en]! }
  }
  for (const key of Object.keys(reviewed)) if (!(key in en)) delete reviewed[key]
  fs.mkdirSync(path.join(root, 'src/i18n/reviewed'), { recursive: true })
  fs.writeFileSync(path.join(root, 'src/i18n/reviewed', `${language}.json`), JSON.stringify(reviewed, null, 2) + '\n')
  console.log(`Acknowledged ${keys.join(', ')} for ${language}; no report command ever marks translations reviewed.`)
} else {
  const report = ['# Translation coverage', '', 'Generated by `npm run i18n:report`. Current means source/translation revisions match the recorded review baseline, not a certification of linguistic quality.', '']
  let invalid = false
  for (const language of LANGUAGES.filter(l => l !== 'en')) {
    const catalog = await languageRegistry[language].load()
    const errors = validateCatalog(en, catalog, languageRegistry[language].locale)
    invalid ||= errors.length > 0
    const states = translationStatus(en, catalog, readReviewed(language))
    const counts = ['current', 'needs review', 'missing'].map(status => `${states.filter(s => s.status === status).length} ${status}`).join(' · ')
    console.log(`${language}: ${counts}`)
    for (const error of errors) console.error(error)
    report.push(`## ${languageRegistry[language].name}`, '', counts, '')
    for (const state of states.filter(s => s.status !== 'current')) report.push(`- **${state.status}** — \`${state.key}\``, `  - Previous English: ${JSON.stringify(state.previousEnglish ?? null)}`, `  - Current English: ${JSON.stringify(state.english)}`)
    report.push(...errors.map(e => `- INVALID: ${e}`), '')
  }
  if (command === 'report') fs.writeFileSync(path.join(root, 'docs/translation-coverage.md'), report.join('\n').trimEnd() + '\n')
  else if (command !== 'check') throw new Error(`Unknown command ${command}`)
  if (invalid) process.exitCode = 1
}
